spring.application.name=order-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/orderdb}
spring.datasource.username=${DB_USERNAME:orderuser}
spring.datasource.password=${DB_PASSWORD:orderpass}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health